# Generated by Django 5.0.3 on 2024-10-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trip_departure_station_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus',
            table=None,
        ),
    ]
